### ISSUE TITLE
Feature: Write entries

### ISSUE THREAD

**Issue by sergiodxa** [codeableorg/diary-app#1]
**Describe the solution you'd like**
As a user, I want to write entries

- [ ] Each entry should have a date.
- [ ] Each entry should have a title limited to 80 characters
- [ ] Each entry should have a content.
  - [ ] The content could have images.
  - [ ] It should support HTML code.

**Comment by Linzeur** [comment]
This feature was completed in this PR:
https://github.com/codeableorg/diary-app/pull/22
