### ISSUE TITLE
Feature: List entries

### ISSUE THREAD

**Issue by sergiodxa** [codeableorg/diary-app#2]
**Describe the solution you'd like**
As a user, I want to have a list of all my entries

- [x] It should be a page with the list of entries.
- [x] Each entry in the list should have the title.
- [x] Each entry in the list should have the description.
- [x] Each entry in the list should have the date.
- [x] Each should link to the entry page to read it.
- [x] The list should be sorted by newest first.
- [x] A highlighted entry (#7) should be displayed with a different style.

**Comment by paulotijero** [comment]
This issues was solved in the following pull -> #19
