### ISSUE TITLE
Feature: Image upload

### ISSUE THREAD

**Issue by sergiodxa** [codeableorg/diary-app#3]
**Describe the solution you'd like**
As a user, I want to be able to upload images to the blog and use them on entries.

- [x] It should support uploading images.
- [x] It should show the image URL after the upload.
- [x] It should have a page to display all the images in a grid

**Comment by Linzeur** [comment]
Show all photos in a grid. Done.
Show the image URL. Done

**Comment by Linzeur** [comment]
This Feature was completed with the following PRs:
https://github.com/codeableorg/diary-app/pull/38/
https://github.com/codeableorg/diary-app/pull/39/
