### ISSUE TITLE
Feature: Delete entries

### ISSUE THREAD

**Issue by sergiodxa** [codeableorg/diary-app#6]
**Describe the solution you'd like**
As a user, I want to be able to delete my entries.

- [x] Each entry should have a delete button.
- [x] The delete should hide the entry completely but keep it stored.
- [ ] A deleted entry should be accessible with the URL for one day after it was deleted before it's completely hidden and have an undo button to recover the post. After the day has passed an article should not be accessible anymore.

**Comment by Linzeur** [comment]
This issue was complemented with the following PR:
https://github.com/codeableorg/diary-app/pull/34
